# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ master ]

jobs:
  tests-python39-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Local install
      run: |
        python -m pip install . --upgrade
    - name: Install Test Deps
      run: |
        python -m pip install pytest coverage pytest-cov
    - name: Tests
      run: |
        pytest --cov=tests

  tests-python38-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Local install
      run: |
        python -m pip install . --upgrade
    - name: Install Test Deps
      run: |
        python -m pip install pytest coverage pytest-cov
    - name: Tests
      run: |
        pytest --cov=tests

  tests-python37-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Local install
      run: |
        python -m pip install . --upgrade
    - name: Install Test Deps
      run: |
        python -m pip install pytest coverage pytest-cov
    - name: Tests
      run: |
        pytest --cov=tests

  tests-python36-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Local install
      run: |
        python -m pip install . --upgrade
    - name: Install Test Deps
      run: |
        python -m pip install pytest coverage pytest-cov
    - name: Tests
      run: |
        pytest --cov=tests


  tests-python39-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Local install
      run: |
        python -m pip install . --upgrade
    - name: Install Test Deps
      run: |
        python -m pip install pytest coverage pytest-cov
    - name: Tests
      run: |
        pytest --cov=tests

  tests-python38-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Local install
      run: |
        python -m pip install . --upgrade
    - name: Install Test Deps
      run: |
        python -m pip install pytest coverage pytest-cov
    - name: Tests
      run: |
        pytest --cov=tests

  tests-python37-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Local install
      run: |
        python -m pip install . --upgrade
    - name: Install Test Deps
      run: |
        python -m pip install pytest coverage pytest-cov
    - name: Tests
      run: |
        pytest --cov=tests

  tests-python36-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Local install
      run: |
        python -m pip install . --upgrade
    - name: Install Test Deps
      run: |
        python -m pip install pytest coverage pytest-cov
    - name: Tests
      run: |
        pytest --cov=tests
